### ISSUE TITLE
Review requirements.txt

### ISSUE THREAD

**Issue by poligarcia** [devartis/django-cms-chunks#1]
There are a bunch of dependencies on requirements.txt that are not needed by django-cms-chunks, but are requisites for the test_app, such as Werkzeug, distribute, sekizai, etc.
My guess is that the requirements of django-cms-chunks are:

Django<1.6
django-cms<2.4

The other dependencies can go on a separate requirements.txt file on the test_app/ directory

**Comment by leandro-gomez** [comment]
These commits should be fix it:
b6407df325bda64c9afdc523e03083640216d692
and
46acd3b5e1fbddf3812fbfc4f4c1db2feb4185fb
